### ISSUE TITLE
question request

### ISSUE THREAD

**Issue by G-Naughty** [csuhan/s2anet#1]
python tools/test.py configs/dota/s2anet_r50_fpn_1x.py \
    work_dirs/s2anet_r50_fpn_1x/epoch_12.pth \ 
    --out work_dirs/ s2anet_r50_fpn_1x/res.pkl
how  to make res.pkl?

**Comment by csuhan** [comment]
Sorry for that, and I have update the docs.
res.pkl is the output file, which records the detection results. It can be any other names, e.g., result.pkl, out.pkl.
For single gpu test, please run:
`python tools/test.py configs/dota/s2anet_r50_fpn_1x.py work_dirs/s2anet_r50_fpn_1x/epoch_12.pth --out work_dirs/s2anet_r50_fpn_1x/res.pkl`
