### ISSUE TITLE
dota map指标问题

### ISSUE THREAD

**Issue by printfxs** [csuhan/s2anet#105]
作者你好：
      非常感谢你的工作，我在复现你的算法中，使用 configs/dota/s2anet_r50_fpn_1x_dota.py，并加载了resnet50预训练模型，lr=0.005 for 2 GPUs * 2 img/gpu，训练后的dota1_task1 map71，与作者的指标差距较大，请问可能是哪些地方出的问题。

**Comment by csuhan** [comment]
请尝试使用原版：https://github.com/csuhan/s2anet/tree/original_version的数据处理和模型训练。新版仅测试cascade-s2anet的精度。

**Comment by printfxs** [comment]
开启多尺度和随机旋转，指标正常了。
