### ISSUE TITLE
the split overlap between patches

### ISSUE THREAD

**Issue by iamstupidd** [csuhan/s2anet#110]
Sorry sir, I just wonder know why u set the overlap to 200 in multiscale training, have u ever tested the map between 200 and 512? thx

**Comment by csuhan** [comment]
`gap=200` is used for single-scale training, `gap=512` is used for multi-scale training.

As some objects in the splitting boundary will be cut into two parts, we set an overlap between two patches to avoid it.

Generally, mAP will increase as the gap increases.

**Comment by iamstupidd** [comment]
> `gap=200` is used for single-scale training, `gap=512` is used for multi-scale training.
> 
> As some objects in the splitting boundary will be cut into two parts, we set an overlap between two patches to avoid it.
>
> Generally, mAP will increase as the gap increases.

prepare_dota1_ms.py[https://github.com/csuhan/s2anet/blob/master/DOTA_devkit/prepare_dota1_ms.py#L51-L52](url)
do u mean it is not ur default setting?

**Comment by iamstupidd** [comment]
> `gap=200` is used for single-scale training, `gap=512` is used for multi-scale training.
> 
> As some objects in the splitting boundary will be cut into two parts, we set an overlap between two patches to avoid it.
> 
> Generally, mAP will increase as the gap increases.

https://github.com/csuhan/s2anet/blob/master/DOTA_devkit/prepare_dota1_ms\.py#L51
u mean it's not ur default setting for paper's results?
thx for ur reply!!!

**Comment by csuhan** [comment]
This is our default setting.
