### ISSUE TITLE
The mAP on DOTA v1.0 can't achieve 74.

### ISSUE THREAD

**Issue by zytx121** [csuhan/s2anet#119]
Same question with #105.  I use 1 GPU to run S2ANet, but only get 72 mAP.  What's difference between master branch and original_version branch cause this problem? And if i still want to use master branch to achieve 74 mAP, what should i do?

**Comment by csuhan** [comment]
The original version does not remove non-object images

**Comment by zytx121** [comment]
OK, thx!
