### ISSUE TITLE
Does s2anet support two stage object detection algorithm? such as Cascade-R-CNN, thanks

### ISSUE THREAD

**Issue by LoveDLWujing** [csuhan/s2anet#16]

**Comment by csuhan** [comment]
For two stage methods, we have only tested [Faster RCNN OBB](https://github.com/csuhan/s2anet/blob/master/configs/dota/faster_rcnn_obb_r50_fpn_1x_dota.py). For other methods like Cascade RCNN, You need to modify related files, e.g., [cascade_rcnn.py](https://github.com/csuhan/s2anet/blob/master/mmdet/models/detectors/cascade_rcnn.py) for HBB-OBB transformations. 
Also, you can take [AerialDetection](https://github.com/dingjiansw101/AerialDetection) as a reference which implements more methods for oriented object detection.
