### ISSUE TITLE
Question about how ARF works

### ISSUE THREAD

**Issue by wuyuanyi135** [csuhan/s2anet#22]
Hello, 
In the arxiv manuscript, I do not understand how ARF works
1.  EQ 5 the Y is calculated as the ARF output, but in EQ 6 the x\hat is the pooled output. Is this x\hat supposed to be y\hat or I misunderstood it?

2. It seems like the ARF is trying to rotate a kernel and compute how the feature map matching different orientation of this filter. If one filter response is high it means the local feature is highly possible aligned in this direction. Am I getting this correctly? Then why should we sum up the output like eq5, rather than keep them in different channels and find the maximum?

3. For EQ.5 when the F rotates, it is misaligned with X. How to compute eq5. By interpolation?

4.I don't understand why 256 channel feature map will become 32 channel feature map after pooling. Could you explain it?

I think my problems are somewhat related. Maybe I missed some fundamental knowledge in NN. 

Thanks for your time and contribution!

**Comment by csuhan** [comment]
1. Yes. We use **X** to represent a feature map in the paper, and **Y** is to distinguish from **X** only in eq.5.
2. sum operation in eq.5 aims to obtain response (features) from all orientations, i.e., orientation sensitive. While max operation in eq.6 aims to find maximum response of all channels, that is orientation invariant. For more details, please refer to [ORN](https://arxiv.org/abs/1701.01833).
3. Yeah, it is difficult to explain clearly here in my knowledge, please refer to [ORN](https://arxiv.org/abs/1701.01833) and [https://github.com/ZhouYanzhao/ORN](https://github.com/ZhouYanzhao/ORN).
4. In eq.6, a feature map e.g., `(2*256*H*W)=(2*32*8*H*W)` with N (=8) orientations becomes `(2*32*H*W)` after pooling.

**Comment by wuyuanyi135** [comment]
@csuhan Thanks for your explanations!
