### ISSUE TITLE
the angle range of the oriented bounding box ?

### ISSUE THREAD

**Issue by lianglele185** [csuhan/s2anet#23]
why tha angle range  of the oriented bounding box is [-pi/4,3pi/4]

**Comment by csuhan** [comment]
This is consistent with our definition of OBBs.
1. For a polygon, we select start point by [get_best_begin_point_single](https://github.com/csuhan/s2anet/blob/daf71a85264a0aa92639e4493f691427e18fabea/DOTA_devkit/dota_poly2rbox.py#L11), i.e., top-left corner of a polygon.
2. When transforming a polygon to a rbox, we select the angle between the long side and the axis-x of the start point as the angle of a rbox. See Fig.3 in our paper.
3. We define the angle in half circle.

These three restrictions determine our angle range `[-pi/4, 3*pi/4]`

**Comment by lianglele185** [comment]
thaks for you explanation. I want to know if the origin of the image is in the top-left corner or the bottom-left corner

**Comment by csuhan** [comment]
The top-left corner, e.g., (0, 0) in the image tensor.
