### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by 2018loveyyq** [csuhan/s2anet#25]
when I run python tools/test.py configs/dota/s2anet_r50_fpn_1x.py /home/lichenglong/s2anet/configs/dota/s2anet_r50_fpn_1x_ms_rotate_epoch_12_20200815.pth --out /home/lichenglong/s2anet/work_dirs/s2anet_r50_fpn_1x/res.pkl --show 
there is an  AssertionError : assert bboxes.shape[1] == 4 or bboxes.shape[1] == 5
the details are as follows:
![image](https://user-images.githubusercontent.com/38448650/96820187-fdefe600-1457-11eb-8e18-7310f70a0095.png)
Is there anyone who has also encountered the same problem?I need for your help,tanks!

**Comment by csuhan** [comment]
Please use [demo/demo_inference.py](https://github.com/csuhan/s2anet/blob/master/demo/demo_inference.py) for visualization.

**Comment by 2018loveyyq** [comment]
Yes,I&nbsp;have tried to run it,but encountered the same error.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csuhan/s2anet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午2:55
收件人:&nbsp;"csuhan/s2anet"<s2anet@noreply.github.com&gt;;
抄送:&nbsp;"十二"<2539372545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [csuhan/s2anet] AssertionError (#25)





 
Please use demo/demo_inference.py for visualization.

**Comment by csuhan** [comment]
Please paste the error log
