### ISSUE TITLE
mmdet

### ISSUE THREAD

**Issue by xuanxiaoliqu** [csuhan/s2anet#26]
version `libcudart.so.10.1' not found

**Comment by csuhan** [comment]
Make sure you have installed cuda-10.1, try `conda install cudatoolkit=10.1`

**Comment by xuanxiaoliqu** [comment]
hello，May I know which version of MMDET you are using

**Comment by xuanxiaoliqu** [comment]
I use mmdet=0.6.0, this requires cuda version to be 10.1

**Comment by xuanxiaoliqu** [comment]
Is your CUDA version 10.1

**Comment by csuhan** [comment]
The version of mmdet is released around Sep 2019. Cuda>=10.0 works well. Please see our [install guide](https://github.com/csuhan/s2anet/blob/master/docs/INSTALL.md).
