### ISSUE TITLE
Is there any way to evaluate the results of DOTA1.5?

### ISSUE THREAD

**Issue by zhenpn** [csuhan/s2anet#29]
I have got the results on DOTA1.5, but the online evaluation server does not work now. I wonder if there any way to evaluate my results.

**Comment by csuhan** [comment]
We will check the evaluation server later.

**Comment by zhenpn** [comment]
> We will check the evaluation server later.

Thanks for your reply. Hope the DOTA1.5 online evaluation server can restore soon.
