### ISSUE TITLE
about the  ImportError: cannot import name 'get_best_rbox' 

### ISSUE THREAD

**Issue by Jnyle** [csuhan/s2anet#30]
when I try to train the dota dataset with the config file "s2anet_r101_fpn_1x_ms_rotate.py", the error description is as follows:
    from .transforms_rbox import (delta2rbox, get_best_begin_point,
ImportError: cannot import name 'get_best_rbox' from 'mmdet.core.bbox.transforms_rbox' 
Could you please solve  this?

**Comment by csuhan** [comment]
fixed in [173ef21](https://github.com/csuhan/s2anet/commit/173ef2151a8163148f414bc65423d9a9f187961a)
