### ISSUE TITLE
AP计算

### ISSUE THREAD

**Issue by FL77N** [csuhan/s2anet#36]
您好，关于mAP的计算，是使用旋转框的iou计算的吗？可以告知一下是哪个文件吗？我只您的文件中找到了适用于用(K ,4)这种形式的ap计算。

**Comment by csuhan** [comment]
Please refer to [https://github.com/csuhan/s2anet/blob/master/DOTA_devkit/dota_evaluation_task1.py]()

**Comment by FL77N** [comment]
> Please refer to https://github.com/csuhan/s2anet/blob/master/DOTA_devkit/dota_evaluation_task1.py

Thank you for your reply!!!
