### ISSUE TITLE
basketball-court.txt文件为空？

### ISSUE THREAD

**Issue by yzk-lab** [csuhan/s2anet#39]
为什么basaketball-court的txt文件是空的呢？
![image](https://user-images.githubusercontent.com/41197028/100498016-2b882780-319a-11eb-863d-1d5da26f9d6d.png)

**Comment by Sp2-Hybrid** [comment]
你好，我想问一下，你按照作者的原始配置文件跑起来正常吗？
我使用作者原始配置文件，文件为configs/dota/s2anet_r50_fpn_1x.py，我在train的过程中发现loss会变成nan，将lr改小之后loss来回波动，最终也会变成nan。。。非常费解。。。

**Comment by yzk-lab** [comment]
> 你好，我想问一下，你按照作者的原始配置文件跑起来正常吗？
> 我使用作者原始配置文件，文件为configs/dota/s2anet_r50_fpn_1x.py，我在train的过程中发现loss会变成nan，将lr改小之后loss来回波动，最终也会变成nan。。。非常费解。。。

正常  就是测试结果有问题，loss一直在下降

**Comment by csuhan** [comment]
I guess your checkpoints is not well trained or configured.

As shown in ```test.py```, (1) please check the output log of each categories during testing. (2) visualize the results to see whether your checkpoint is 'correct'. Also, you can download the checkpoints provided by us to verify the results.
https://github.com/csuhan/s2anet/blob/173ef2151a8163148f414bc65423d9a9f187961a/tools/test.py#L223-L236

**Comment by yzk-lab** [comment]
谢谢你的回复，我已经解决了这个问题并且取得了较高的map.现在我有个新问题，就是如果我要训练自己的数据集（800x600的jpg文件和DOTA的png不太一样)，我数据集标签是8个点的坐标的形式。我转成VOC格式可以做吗？因为我不想使用prepare_dota.py去处理数据集了。

**Comment by csuhan** [comment]
跟annotation的原始格式没有关系。但模型在训练时需要回归bbox的角度，因此在preprocessing之后必须转成（x,y,w,h,a）的形式。
如果原始数据是8点的polygon，则需要自定义一个dataset，读入8参数，输出5参数的形式，因此最终的数据格式和[dota_obb](https://github.com/csuhan/s2anet/blob/master/mmdet/datasets/dota_obb.py)应该是一样的。
