### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by ming71** [csuhan/s2anet#4]
Could you please provide with trained RetinaNet model? Thanks!

**Comment by csuhan** [comment]
We are sorry that all the pretrained models have been deleted accidentally when sorting the code.
And we will provide more models later.

**Comment by ming71** [comment]
Thanks!

**Comment by csuhan** [comment]
Hi, @ming71 , RetinaNet on DOTA is avaliable at [here](https://drive.google.com/file/d/1ZUc8VUDOkTnVA1FFNuINm2U39h0anLPm/view?usp=sharing).

**Comment by ming71** [comment]
thanks, really a nice work! I've trained myself, and similar result have been achieved.
