### ISSUE TITLE
--show problem 

### ISSUE THREAD

**Issue by yzk-lab** [csuhan/s2anet#40]
dear  author:
can you help me to solve this prolem? whether i can directly get the visiual  result by this  command?
CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/dota/s2anet_r101_fpn_1x_ms_rotate.py yzk_work_dirs/s2anet_r101_fpn_1x_ms_rotate/epoch_12.pth --show

when i run it ,it occurs error. 
![image](https://user-images.githubusercontent.com/41197028/100875427-f56fde00-34e0-11eb-92a1-e149394a909a.png)
hope  for your reply.i want to apply this detection project on real-time detection,if i can do it?thanks for your reply and directions.

**Comment by csuhan** [comment]
1. Please use [demo/demo_inference.py](https://github.com/csuhan/s2anet/blob/master/demo/demo_inference.py) for visualization.
2. It is still hard to realize real-time detection (>30fps) unless you reduce the image size and adopt more powerful GPU. Besides, a fast version of s2anet in TABLE V of our paper may help you.

**Comment by yzk-lab** [comment]
thanks for your reply. i have learned your paper  but i have some problem in some details  in  FAM module and ODM module.
1. i want to read the code,where i can directly learn the FAM and ODM? are they in  s2anet -
 master/mmdet/models/anchor_heads/s2anet.py or  other heads? 
2.i want to understand the ARN  how  works to refine  the horizontal anchor  into rotation  anchor with high-quality?by regression? and high-guality means what?  if it works by regression,whether the metrics is the iou with the groundtruth?
3. then i want t know whether i define some initial angles?
sorry, I propose many problems,this might occupy your time,but i really hope for your reply.thanks!thanks!thanks!

**Comment by yzk-lab** [comment]
thanks for your reply. i have learned your paper but i have some problem in some details in FAM module and ODM module.

i want to read the code,where i can directly learn the FAM and ODM? are they in s2anet -
master/mmdet/models/anchor_heads/s2anet.py or other heads?
2.i want to understand the ARN how works to refine the horizontal anchor into rotation anchor with high-quality?by regression? and high-guality means what? if it works by regression,whether the metrics is the iou with the groundtruth?
3.then i want t know whether i define some initial angles?
sorry, I propose many problems,this might occupy your time,but i really hope for your reply.thanks!thanks!thanks!

**Comment by csuhan** [comment]
1. Yes. Most codes related to s2anet lie in mmdet/models/anchor_heads/s2anet.py.
2. You can regard ARN as a light RetinaNet or a region proposal network.
3. You dont need to define the initial angles, ARN can automatically refine horizontal anchors into oriented anchors.

**Comment by yzk-lab** [comment]
thanks for your rply.
where i can  learn the process that  the  ARN  turns the horizontal  anchor into rotation? i don't understand the operation why the ARN can refine  a standard axis-aligned anchor into  high-quality  rotated anchor if the regression process without the angle parameter.Dear author,can you direct me for more information?  thanks.thanks.thanks.

**Comment by csuhan** [comment]
![image](https://user-images.githubusercontent.com/17927516/101736431-58273200-3afe-11eb-8d23-53e83f472155.png)

https://github.com/csuhan/s2anet/blob/173ef2151a8163148f414bc65423d9a9f187961a/mmdet/models/anchor_heads/s2anet_head.py#L470-L498

**Comment by yzk-lab** [comment]
谢谢你的回复，对我很有帮助。我想再问一下。
1.这个ARF模块是不是一个四维的filter(m*n*w*h)m表示卷积核数量(m表示方向，n表示卷积核个数，w,h表示宽高）？它如何作用在w*h*n的feature map呢？这不是维度不一致吗？
![image](https://user-images.githubusercontent.com/41197028/102004796-ebef3d00-3d4e-11eb-90f7-4cf7df052c39.png)
2.为什么X(n)可以表示X的第n个方向通道，X是feature map不是没有方向通道吗？
3.Y(i)指的是在某一个角度下将8个方向通道相加堆叠吗？希望可以点拨我一下这里，确实有点迷糊。
感谢，感谢，感谢。

**Comment by yzk-lab** [comment]
谢谢你的回复，对我很有帮助。我想再问一下。
1.这个ARF模块是不是一个四维的filter(mnwh)m表示卷积核数量(m表示方向，n表示卷积核个数，w,h表示宽高）？它如何作用在w*h*n的原始的feature map上呢？这不是维度不一致吗？
![image](https://user-images.githubusercontent.com/41197028/102005004-9ddb3900-3d50-11eb-9332-ec93d756db8c.png)

2.为什么X(n)可以表示X的第n个方向通道，X是FAM模块输入的feature map不是没有方向通道吗？
3.Y(i)指的是在某一个角度下将8个方向通道相加堆叠吗？希望可以点拨我一下这里，确实有点迷糊。
感谢，感谢，感谢。
