### ISSUE TITLE
mAP in TABLE VII in the paper

### ISSUE THREAD

**Issue by wangjue-wzq** [csuhan/s2anet#41]
I noticed that RetinaNet mAP using R-101-FPN is 68.72 in TABLE VII. Can you tell me where the data comes from? I used this code（https://github.com/dingjiansw101/AerialDetection/blob/master/configs/DOTA/retinanet_obb_r50_fpn_2x_dota.py） for training, and the result was only about 40 mAP. Thank you!

**Comment by csuhan** [comment]
We use both training and validation sets of DOTA for training. The result of ours (RetinaNet-R50) is similar to AerialDetection, 68.40 vs 66.28.

**Comment by wangjue-wzq** [comment]
Thanks！
