### ISSUE TITLE
loss became NaN when traning with multi-scale dataset

### ISSUE THREAD

**Issue by Hu01001** [csuhan/s2anet#42]
Hello, I configured the multi-scale dataset, used the DOTA1.5 tag, and modified the num_classes configuration, but the other configurations were not modified. When I was training, loss dropped at the beginning, but suddenly became NaN. I want to know if this is due to a code problem or my wrong dataset configuration.
Using the dota1.0 dataset, I can train well.Thanks for your attention and reply!
![ss](https://user-images.githubusercontent.com/36106081/101349875-f336c680-38c8-11eb-8d3d-9da673e9d5db.png)

**Comment by csuhan** [comment]
1. please check the learning rate. 
0.01lr=4GPU\*2img/GPU
0.0025lr=1GPU\*2img/GPU
2. Filtering out some small instances (<10px) may help the trainning.

**Comment by Hu01001** [comment]
OK,my learning rate is 0.01lr=4GPU*2img/GPU, and I will try the second solution you mentioned,Thanks for your suggestion.
