### ISSUE TITLE
Is there any problem with the rotated rectangle representation?

### ISSUE THREAD

**Issue by ming71** [csuhan/s2anet#43]
Hello, thank you for your excellent work.
I have achieved good performance on HRSC2016 with your implementation by adding an extra anchor refinement module(Refined-RetinaNet), but there are many redundant boxes in the detection results. I don't know whether it is caused by your rbox representation. And this may be the reason for the poor performance achieved by RetinaNet here?
In addition, I implemented a retinanet for polygon prediction, and there are still many redundant rotated boxes with high-confidence . Does the problem come from the data loader?
![100001048](https://user-images.githubusercontent.com/43720092/101747594-ab04e780-3b06-11eb-9f17-03878d4568db.jpg)
![100001410](https://user-images.githubusercontent.com/43720092/101747689-b0623200-3b06-11eb-9ca2-29c612fa13d2.jpg)
![100000763](https://user-images.githubusercontent.com/43720092/101747919-cff95a80-3b06-11eb-8c26-5bf7a6e4154f.jpg)
![100001180](https://user-images.githubusercontent.com/43720092/101747963-e3a4c100-3b06-11eb-8d79-d93d6cd73ce1.jpg)

**Comment by csuhan** [comment]
From our experiments, we noticed that HRSC2016 is very sensitive to the lr and schedule. Take the 3x s2anet as an example, it may get promising results at 1x, but significantly drop at 2x, and obtians the best result at 3x. I guess: (1) HRSC2016 is too samll. RetinaNet performs well on DOTA. (2) For the ship instance (x,y,w,h,a), w,h>>a, making it difficult for the angle to converge accurately.

Besides, I think my rbox representation is correct. It limit the angle between [-pi/4, 3*pi/4] for fast convergence. All the transformations between bbox, rbox and polygon have been tested. 

I will try RetinaNet on HRSC2016 soon, but no GPUs are avaliable now🤷‍♀️

[AerialDetection](https://github.com/dingjiansw101/AerialDetection) is more strong and powerful, and you may want to try it.

**Comment by ming71** [comment]
Thank you again for the reply and your great work ! :laughing:
