### ISSUE TITLE
Training with custom dataset 

### ISSUE THREAD

**Issue by srikanthmg85** [csuhan/s2anet#46]
Hi, I am training s2anet with my custom dataset for which I need to estimate oriented bounding boxes. I have modified input resolution and anchor scales as per my requirement along with support for new dataset, following is logs for one of the epoch. Could you let me know if something else needs to be modified for experimenting with custom dataset? 

**loss_fam_cls: nan, loss_fam_bbox: nan, loss_odm_cls: 0.3204, loss_odm_bbox: nan**

**Comment by csuhan** [comment]
You may need to check your data loader first, then follow the lr schedule: 0.01lr = 4GPU * 2img/GPU.

**Comment by bangbox2** [comment]
> Hi, I am training s2anet with my custom dataset for which I need to estimate oriented bounding boxes. I have modified input resolution and anchor scales as per my requirement along with support for new dataset, following is logs for one of the epoch. Could you let me know if something else needs to be modified for experimenting with custom dataset?
> 
> **loss_fam_cls: nan, loss_fam_bbox: nan, loss_odm_cls: 0.3204, loss_odm_bbox: nan**

Hello, have you solved it? I also encountered this problem recently
