### ISSUE TITLE
the size of the gt_bboxes and the gt_labels is inconsistent

### ISSUE THREAD

**Issue by Jnyle** [csuhan/s2anet#50]
hey, 
when I try to modify some code ,and print the shape of two tensors as following in the anchor_target_single_obb_obb_rbox.py file and find that they are inconsistent:

gt_bboxes: torch.Size([324, 5])
gt_labels: torch.Size([343])

is this right?

**Comment by csuhan** [comment]
You may need to check your dataset. Try to print the variables. They should be always the same size.

**Comment by Jnyle** [comment]
> You may need to check your dataset. Try to print the variables. They should be always the same size.

Thank you for your reply, and I will check it carefully.
