### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by gengyanlei** [csuhan/s2anet#52]
作者，你好，按照你的readme，安装好后，执行demo代码，输出的都是未检测出来的。即使用dota数据集

**Comment by chenruitao123** [comment]
@csuhan 作者您好，我有一些问题已发送至您的邮箱hanjiaming@whu.edu.cn，期待您的回复，非常感谢

**Comment by csuhan** [comment]
@gengyanlei 请具体地描述问题。

**Comment by chenruitao123** [comment]
s2anet的作者您好，我是中国矿业大学（北京）的一名大学生，最近在github上看到您的s2anet的文章，试着按照步骤做了一下，感到对我特别有帮助，不过在进行处理DOTA数据集时遇到了一些问题，具体情况我在附件中详细说明了一下，希望您能抽时间帮我解决一下我的疑问，万分感谢，期待您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csuhan/s2anet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 中午1:56
收件人:&nbsp;"csuhan/s2anet"<s2anet@noreply.github.com&gt;;
抄送:&nbsp;"期待┌;崛起`灬"<1404917233@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [csuhan/s2anet] 问题 (#52)





 
@gengyanlei 请具体地描述问题。

**Comment by gengyanlei** [comment]
作者，你好，我安装好s2anet后，执行demo.py，测试DOTA的图像，发现每个图像都预测不出来，是不是权重没有加载进去呢？

**Comment by csuhan** [comment]
To inference multiple images in a folder, you can run:

```python demo/demo_inference.py ${CONFIG_FILE} ${CHECKPOINT} ${IMG_DIR} ${OUTPUT_DIR}```

请确保config和checkpoint之间的对应关系。另外建议在issue中附上console的log。

**Comment by gengyanlei** [comment]
@csuhan 
你好，我完全是按照你的readme进行设置的，然后运行测试无论什么样的图像 均无法测试出结果

**Comment by tjmannn** [comment]
@gengyanlei 你好，我也遇到了一样的问题，demo_inference和test对dota都没有检测结果，像test能产生15类别文件，但是全是空文件，demo产生的图也是原图

**Comment by gengyanlei** [comment]
不清楚哪里出现了问题。目前在旋转目标检测里面的项目，普遍都或多或少有问题，然后代码风格也有点问题，想找1个好改的，期待1个合适的项目。自己写代码量太大，没时间写啊

**Comment by csuhan** [comment]
#61

**Comment by gengyanlei** [comment]
@csuhan 不过我没有训练，而是直接用你的权重 直接inference的，也是不出结果。

**Comment by csuhan** [comment]
请附上对应的log

**Comment by gengyanlei** [comment]
你的inference.py哪有什么输出log啊，我就是按照你的inference步骤执行的，但是没有输出，总是强调log，你的代码又没有报错，封装的有点抽象，我也不知道哪里有问题啊，尴尬。

**Comment by tjmannn** [comment]
@gengyanlei 你可以把inference里面的result打印一下看看是什么，或者把你检测结果的pkl读取一下看看是什么

**Comment by csuhan** [comment]
@gengyanlei 
1. 程序无法正常运行的原因有很多种，我没有义务去解决每个人遇到的问题。
2. 你的提问对解决这个问题没有任何价值。

**Comment by gengyanlei** [comment]
好吧！

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/109641908-3ed9d300-7b8d-11eb-8b95-f05da0e91a57.png)
inference里面的result全部为空，即使是DOTA的数据也为空
@tjmannn
