### ISSUE TITLE
bug in RandomRotate

### ISSUE THREAD

**Issue by WhiteCipher** [csuhan/s2anet#53]
in https://github.com/csuhan/s2anet/blob/master/mmdet/datasets/pipelines/transforms_rotated.py#L162
It looks that the key "labels" should be "gt_labels" ? BTW, there is no rotation code for gt_bboxes_ignore.

**Comment by WhiteCipher** [comment]
relates to #50 , this bug may cause inconsistency between number of gt_bboxes and gt_labels.

**Comment by csuhan** [comment]
Thank you for your suggestion! This is indeed a bug for that most codes about `RandomRotate` are modified from detectron2.

The `labels` bug may affect the training but not crucial. We have noticed the `gt_bboxes_ignore` bug. As this field is not involved in the model's  `forward`, we ignore it. (。_。)

This bug will be fixed.
