### ISSUE TITLE
The problem of confidence

### ISSUE THREAD

**Issue by gewenchao** [csuhan/s2anet#54]
Hello, I used your model. The map performed very good, but the confidence of the demo does not seem to be very high. I using the model of Ding Jian’s RoI Transformer, the confidence of the demo looks very high, like airplanes and ships, etc., reaching 0.99 , what is the reason,thank you.

**Comment by gewenchao** [comment]
Is it related to the threshold set during training？

**Comment by csuhan** [comment]
It may be related to the assignment thr in both FAM and ODM. We set it to 0.4-0.5 in both modules for a higher final mAP.

RoITrans performs well on AP75 and AP50-95, so its cls_score may be higher than S<sup>2</sup>A-Net.

**Comment by gewenchao** [comment]
> It may be related to the assignment thr in both FAM and ODM. We set it to 0.4-0.5 in both modules for a higher final mAP.
> 
> RoITrans performs well on AP75 and AP50-95, so its cls_score may be higher than S2A-Net.

ok, thank you very much
