### ISSUE TITLE
支持UCAS_AOD数据集吗

### ISSUE THREAD

**Issue by vs-learner-llg** [csuhan/s2anet#55]
大佬，请问这个算法模型可以训练UCAS_AOD数据集，又训练好的map吗？

**Comment by csuhan** [comment]
理论上可以训练。[这里](https://github.com/ming71/UCAS-AOD-benchmark)汇报有S<sup>2</sup>A-Net在UCAS_AOD的结果。将这个数据集添加进repo应该比较容易，后续我们可能会增加这个数据集。
