### ISSUE TITLE
how to apply the code for Dotav1.5?

### ISSUE THREAD

**Issue by nishit01** [csuhan/s2anet#57]
I have made changes to the number of classes and appended class name "container-crane" within the code?
But after epoch-1 of training from configs/dota/s2anet_r50_fpn_1x_dota.py, the container-crane.txt in the results_before_nms directory is empty?

If someone has tried on Dotav1.5, it would be a great help to know what are the changes to make it work for dota v1.5?

**Comment by csuhan** [comment]
1. Change `CLASSES` [here](https://github.com/csuhan/s2anet/blob/2f73486261eccbc5c251fdc7a1450a0f88d9ceae/mmdet/datasets/dota.py#L15)
2. Change `num_classes` [here](https://github.com/csuhan/s2anet/blob/2f73486261eccbc5c251fdc7a1450a0f88d9ceae/configs/dota/s2anet_r50_fpn_1x_dota.py#L21)

Notice that the AP of `container-crane` with `s2anet (12 epochs)` is around `10%`. So it may work after longer training schedule.

**Comment by nishit01** [comment]
Thanks @csuhan
