### ISSUE TITLE
To obtain the current epoch

### ISSUE THREAD

**Issue by Jnyle** [csuhan/s2anet#58]
Hi, can I get the current epoch in the mmdet/models/anchors_head/s2anet_head.py file ?

**Comment by csuhan** [comment]
The training api depends on [mmcv](https://github.com/open-mmlab/mmcv). To obtain the `epoch` variable, please refer to mmcv, e.g., [https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py)
