### ISSUE TITLE
How to evaluate a model trained from the HRSC2016 dataset?

### ISSUE THREAD

**Issue by ZegWe** [csuhan/s2anet#59]
I tried to use tools/test.py and it shows 
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/dota_1024/test_split/test_s2anet.pkl'
```
when I'm trying to use test_robustness.py, it shows
```
AttributeError: 'HRSC2016Dataset' object has no attribute 'img_norm_cfg'
```

**Comment by csuhan** [comment]
Test S<sup>2</sup>A-Net on HRSC2016. Refer to [docs/GETTING_STARTED.md](https://github.com/csuhan/s2anet/blob/master/docs/GETTING_STARTED.md) for more details.
```
python tools/test.py configs/dota/s2anet_r50_fpn_1x.py \
    work_dirs/s2anet_r50_fpn_1x/epoch_12.pth \ 
    --out work_dirs/s2anet_r50_fpn_1x/res.pkl \
    --data hrsc2016
```

**Comment by ZegWe** [comment]
> Test S2A-Net on HRSC2016. Refer to [docs/GETTING_STARTED.md](https://github.com/csuhan/s2anet/blob/master/docs/GETTING_STARTED.md) for more details.
> 
> ```
> python tools/test.py configs/dota/s2anet_r50_fpn_1x.py \
>     work_dirs/s2anet_r50_fpn_1x/epoch_12.pth \ 
>     --out work_dirs/s2anet_r50_fpn_1x/res.pkl \
>     --data hrsc2016
> ```

I used this command exactly, but it raised the first error I mentioned above

**Comment by csuhan** [comment]
ohhh, im sorry that it should be 
```
python tools/test.py configs/hrsc2016/s2anet_r50_fpn_3x_hrsc2016.py \
    work_dirs/s2anet_r50_fpn_3x_hrsc2016/epoch_36.pth \ 
    --out work_dirs/s2anet_r50_fpn_3x_hrsc2016/res.pkl \
    --data hrsc2016
```

**Comment by ZegWe** [comment]
> ohhh, im sorry that it should be
> 
> ```
> python tools/test.py configs/hrsc2016/s2anet_r50_fpn_3x_hrsc2016.py \
>     work_dirs/s2anet_r50_fpn_3x_hrsc2016/epoch_36.pth \ 
>     --out work_dirs/s2anet_r50_fpn_3x_hrsc2016/res.pkl \
>     --data hrsc2016
> ```

the same error, where could I get the 'data/dota_1024/test_split/test_s2anet.pkl' file?

**Comment by csuhan** [comment]
I tested this command again, and it works well for HRSC2016. Please download the corresponding checkpoint we provided here and test it again.

`test_s2anet.pkl` is the annotations of DOTA. If this error occurs again, I guess you are running a wrong config file.

**Comment by ZegWe** [comment]
I rechecked my code and it works well now, thanks

**Comment by Lg955** [comment]
when I want to inference an image, I got the error `FileNotFoundError: [Errno 2] No such file or directory: 'data/dota_1024/test_split/test_s2anet.pkl'`, so I first should run test.py to gain the `test_s2anet.pkl ` before inference?
