### ISSUE TITLE
MultiScale config in config file

### ISSUE THREAD

**Issue by WJ1214** [csuhan/s2anet#6]
Hi! this is a nice work. the best result in your paper is trained and tested by multiscale,  but in your DOTA config file all the train and test pipeline is simple scale. So what is your multiscale train and test config? Thank you
![image](https://user-images.githubusercontent.com/51085092/93449566-7cacad00-f907-11ea-94b2-dd4e29762394.png)
![image](https://user-images.githubusercontent.com/51085092/93449642-91894080-f907-11ea-993b-de31b87178a7.png)

**Comment by csuhan** [comment]
Hi, @WJ1214. In other datasets, like COCO, we can simply add:
```dict(type='Resize', img_scale=[(1280, 1024), (1024, 800), (800, 600)])```
for multiscale training.
But in DOTA, we have to set a param 'gap' (e.g., 200) to ensure that adjacent chip images have an overlap with each other.
So we have to prepare all the samples before training, i.e., offline mode. You can refer to [here](https://github.com/csuhan/s2anet/blob/56c86424f56ccaa0ee8385e7360204f82eaa3e14/DOTA_devkit/prepare_dota1_ms.py#L85) for multiscale dataset preparation. 
For online multiscale training, we have not tested yet.
