### ISSUE TITLE
谢谢！！急求！请问计算tensor(N,5)的两个旋转框的IOU的源码在哪个文件下

### ISSUE THREAD

**Issue by yzk-lab** [csuhan/s2anet#62]
你好，我现在在处理IOU，但是在mmdet,core或者bbox下都只看到了处理(N,4）张量的IOU的方法，我想知道在哪里有计算旋转框IOU的代码？这个s2anet项目里是否有提供？谢谢！

**Comment by csuhan** [comment]
Please refer to [Here](https://github.com/csuhan/s2anet/blob/master/mmdet/core/bbox/iou_calculators/iou2d_calculator_rotated.py)

**Comment by yzk-lab** [comment]
thanks for your reply.I have know how to get IOU.there exists another problem.i want to replace the smoothl1loss with iou loss .but i print the bbox_pred and target ,i found the target is a tensor with 0.so the IOU bwtween the target and pred is 0,therefore my  iou loss is NAN.if i want to use the iou ,how can i output the  iou between the anchor and gt_bbox?i cannot get the IOU between the pred and target.hope for your reply.this problem have puzzle me for a long time.

**Comment by yzk-lab** [comment]
i used your original s2anet to replace the smooth-L1loss with iou loss .it failed

**Comment by csuhan** [comment]
To use IoU as the loss metrics, I suggest the PIoU loss: https://github.com/clobotics/piou

**Comment by yzk-lab** [comment]
are there any solution with IOU by your s2anet?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csuhan/s2anet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csuhan/s2anet] 谢谢！！急求！请问计算tensor(N,5)的两个旋转框的IOU的源码在哪个文件下 (#62)





 
To use IoU as the loss metrics, I suggest the PIoU loss: https://github.com/clobotics/piou

**Comment by yzk-lab** [comment]
sorry to bother you.can you tell me input parameters (the pred and target )in loss function where i can touch,it seems i can not understand the target why the anchor_target is a tensor only include zero.i need to know the meaning of pred and target.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csuhan/s2anet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csuhan/s2anet] 谢谢！！急求！请问计算tensor(N,5)的两个旋转框的IOU的源码在哪个文件下 (#62)





 
To use IoU as the loss metrics, I suggest the PIoU loss: https://github.com/clobotics/piou
