### ISSUE TITLE
getting errors when run setup.py

### ISSUE THREAD

**Issue by dqs27** [csuhan/s2anet#64]
In file included from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from mmdet/ops/nms/src/nms_cuda.cpp:2:
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
error: command 'gcc' failed with exit status 1

**Comment by csuhan** [comment]
Try Pytorch=1.3 or [here](https://github.com/csuhan/ReDet/issues/1)
