### ISSUE TITLE
About flip in test

### ISSUE THREAD

**Issue by OYLH** [csuhan/s2anet#65]
I have read your code find that the bboxes didn't do randomflip after detect in get_bboxes function.
Is that correct? Cause I think if your image do flip but bboxes didn't do, image and bboxes may can't match.

**Comment by csuhan** [comment]
RandomFlip is disabled during testing.
 
https://github.com/csuhan/s2anet/blob/b3717a41796a83d0a5ac9afb02cec36af7e411f0/configs/dota/s2anet_r50_fpn_1x_dota.py#L105-L108
