### ISSUE TITLE
update_version hrsc2016

### ISSUE THREAD

**Issue by yzk-lab** [csuhan/s2anet#66]
hi,i have tried your new version s2anet ,but the configs about hrsc 2016  seems  different  with original version. the ann_file  ends with .txt?what does it means ?the .txt only include the pic name ,so where the annotations?
![image](https://user-images.githubusercontent.com/41197028/112106337-8087f780-8be8-11eb-8dfd-57e129999275.png)

**Comment by csuhan** [comment]
Yes. It only records the pic names. See [INSTALL.md](https://github.com/csuhan/s2anet/blob/master/docs/INSTALL.md)
