### ISSUE TITLE
下载预训练模型后运行test.py出现The model and loaded state dict do not match exactly.的情况

### ISSUE THREAD

**Issue by zixuan19971114** [csuhan/s2anet#67]
作者您好！我按照您的步骤配置好了环境并下载了预训练权重，在DOTA数据集上运行test.py文件时，出现下列的情况：
![image](https://user-images.githubusercontent.com/54736978/112461712-2f6c3500-8d9b-11eb-98cd-5bac869ffedc.png)
并且生成的结果txt文件全部为空，请问该如何解决呢？
我下载的是original_version的代码，下载了下图中倒数第二个权重
![image](https://user-images.githubusercontent.com/54736978/112462015-8d991800-8d9b-11eb-94e9-667114ae04d1.p
希望能得到您的解答！

**Comment by zixuan19971114** [comment]
权重下载了倒数第二个
![image](https://user-images.githubusercontent.com/54736978/112462229-ca650f00-8d9b-11eb-81c3-b9b59d0d6dc9.png)

**Comment by csuhan** [comment]
猜测你可能使用的还是新版的代码，clone指定版本：
```
git clone -b original_version https://github.com/csuhan/s2anet.git
```
