### ISSUE TITLE
四边形的标注是怎么转成旋转框的呢？

### ISSUE THREAD

**Issue by Lie-huo** [csuhan/s2anet#69]
dota数据的任务1是旋转框检测，那么四边形标注的是怎么转成旋转框的呢，旋转框是怎么表示的？

**Comment by csuhan** [comment]
https://github.com/csuhan/s2anet/blob/b3717a41796a83d0a5ac9afb02cec36af7e411f0/DOTA_devkit/convert_dota_to_mmdet.py#L18-L36

**Comment by Lie-huo** [comment]
> https://github.com/csuhan/s2anet/blob/b3717a41796a83d0a5ac9afb02cec36af7e411f0/DOTA_devkit/convert_dota_to_mmdet.py#L18-L36

嗯嗯，好的，这个是针对规则的四边形的处理方式吧，也就是四个边两两平行的四边形，而我的场景是非规则的四边形，所以这种处理方式还是有点问题，应该采用opencv中最小矩形来计算角度了
