### ISSUE TITLE
batch inference_detector

### ISSUE THREAD

**Issue by jorgegonzalezv** [csuhan/s2anet#73]
Hello,

Is batching supported in mmdet.apis inference_detector?

The description says it accepts list of numpy.ndarrays, but i get the following message when passing it such a list:

raise TypeError('"img" must be a numpy array or a filename')

**Comment by csuhan** [comment]
Current version of mmdet that s2anet used does not support batch inference.
But you can modify it from mmdet_v2 which support batch infer.
See:
https://github.com/open-mmlab/mmdetection/blob/931d96e5441b99227dce101ebace5d60c2853830/mmdet/apis/inference.py#L89-L152
