### ISSUE TITLE
为什么dota的trainval切割完后有21046张图片，但写入到trainval_s2anet.pkl文件中只有13557张图片数据。

### ISSUE THREAD

**Issue by gaorui369** [csuhan/s2anet#74]
您好，我用DOTA_devkit/prepare_dota1_ms.py切割完DOTA数据集后，trainval_split文件夹下共有21046张图片，也生成了对应的trainval_s2anet.pkl文件，我用单GPU进行训练，config文件中 imgs_per_gpu=2,workers_per_gpu=2，

但是训练时显示每个epoch只迭代6779张图片，照理应该需要迭代 21046/2= 10523 张图片呀。于是我查看了trainval_s2anet.pkl文件中的内容，发现里面只有13557张图片的数据。而test_s2anet.pkl中的内容与test_split中的图片数量又是对应的，我不知道是哪里出现了问题？

**Comment by csuhan** [comment]
https://github.com/csuhan/s2anet/blob/935b0065f82e35c4224eb24c44c14b91575d5374/DOTA_devkit/convert_dota_to_mmdet.py#L63-L65

**Comment by Savid-mask777** [comment]
> https://github.com/csuhan/s2anet/blob/935b0065f82e35c4224eb24c44c14b91575d5374/DOTA_devkit/convert_dota_to_mmdet.py#L63-L65

非常感谢您！请问去掉没有GT的图像会对训练结果有什么影响吗？
