### ISSUE TITLE
When testing: CUDA ERROR: device-side assert triggered

### ISSUE THREAD

**Issue by galaxyGGG** [csuhan/s2anet#75]
I trained with DOTA data(very small part of the dataset), and with the .pth file I got, I tried to run demo_inference.py but got this error:
CUDA ERROR: device-side assert triggered

please help!

![2021-05-12 15-45-07屏幕截图](https://user-images.githubusercontent.com/45815385/117938434-9e94ed00-b339-11eb-9b1b-4458193747f3.png)

**Comment by chandlerbing65nm** [comment]
@galaxyGGG @csuhan how did you solve this problem?
