### ISSUE TITLE
Can you provide model and log file about CS2A-Net-2s-IoU?

### ISSUE THREAD

**Issue by yingyu13** [csuhan/s2anet#76]
thanks for your work! I cannot find the model and log file about CS2A-Net-2s-IoU, can you update them please?

**Comment by kgiannakelos** [comment]
@csuhan Any updates on this?

**Comment by kgiannakelos** [comment]
@yingyu13  The model and its logs exist in this [link](https://drive.google.com/drive/folders/1Dgzh5dSzzl_hi34KW2HLoHsDcJG_90vE)

@csuhan But the config file is missing (the link is broken). Can you please upload the config file?

**Comment by vpeopleonatank** [comment]
I found it in readme under 
** 20210104 updated version** section 
 https://drive.google.com/drive/folders/1Dgzh5dSzzl_hi34KW2HLoHsDcJG_90vE?usp=sharing
