### ISSUE TITLE
旋转框是如何定义的？

### ISSUE THREAD

**Issue by gaorui369** [csuhan/s2anet#77]
您好，请问将旋转框转化为多边形表示时，您的代码对旋转框的定义采用的是opencv定义法（角度范围在[-pi/2,0）)吗?

> 
![1620809981(1)](https://user-images.githubusercontent.com/70190514/117948830-1831d880-b344-11eb-9cdf-1d229103c277.jpg)

**Comment by csuhan** [comment]
1. 旋转框 (x,y,w,h,a)->多边形 (x1,y1,...,x4,y4)与角度定义区间无关。
2. 多边形->转旋转框可参考: #23
