### ISSUE TITLE
公式理解

### ISSUE THREAD

**Issue by Lg955** [csuhan/s2anet#78]
请问公式(3)的具体意义是什么？怎么在图上表示出来？ 公式(7) ∆xg=……中，R(θ)*(1/w, 1/h)的含义是什么？
![image](https://user-images.githubusercontent.com/69025725/118797531-4462d180-b8cf-11eb-938f-132eabcb3acf.png)
![image](https://user-images.githubusercontent.com/69025725/118797584-56dd0b00-b8cf-11eb-88f2-20aa52757f6a.png)

**Comment by csuhan** [comment]
1. (3)用来计算对齐后采样点的位置，参考Fig.4 (d)中蓝色的点。
2. bbox transform, 将absolute GT编码为relative offset (GT).

**Comment by Lg955** [comment]
您好，我还有两个问题需要请教一下。

1. 公式3中1/k(w, h)的作用是什么呢？（我的理解中1/S是将对应于原始img的anchor缩放到对应FPN的feature上，但是我没理解1/k(w, h)的作用）

2. 公式7中乘以R(theta)是将倾斜框又变回了水平框，以水平框为目标进行回归吗？
