### ISSUE TITLE
计算mAP时报错

### ISSUE THREAD

**Issue by galaxyGGG** [csuhan/s2anet#83]
在运行test.py计算mAP时，会出现如下报错，初步自己判断是由于没有检测到结果造成的，请问这个判断是否正确？

如果正确，是否可以直接返回该类别的AP为0？

![mmexport1622682528269](https://user-images.githubusercontent.com/45815385/120570846-90735180-c44b-11eb-8c06-251fe46ea715.png)

我的修改方式是：在dota_evaluation_task1.py
第152行加入：

`# 判断是否为空
if len(lines)==0:
    return 0, 0, 0`

**Comment by csuhan** [comment]
是的，某一类没有检测结果时会报错
