### ISSUE TITLE
Code of poly overlaps 

### ISSUE THREAD

**Issue by LiWentomng** [csuhan/s2anet#85]

**Comment by LiWentomng** [comment]
你好，感谢代码分享！ 
在[iou2d_calculator_rotated.py](https://github.com/csuhan/s2anet/blob/master/mmdet/core/bbox/iou_calculators/iou2d_calculator_rotated.py)中，42行的bbox_overlaps_rotated函数需要参数的format为（x,y,w,h,a）。在我的代码中，我直接回归四边形的四个点坐标(x1,y1,x2,y2,x3,y3,x4,y4)，然后再转成 rbox（x,y,w,h,a），才能采用[iou2d_calculator_rotated.py](https://github.com/csuhan/s2anet/blob/master/mmdet/core/bbox/iou_calculators/iou2d_calculator_rotated.py)进行assign，则发现掉点十分严重，  我发现大概率是因为poly(x1,y1,x2,y2,x3,y3,x4,y4)转rbox(x,y,w,h,a)这一过程中存在误差（特别是对于接近正方形）。我也尝试DOTA_devkit工具包中的[polyiou.py](https://github.com/csuhan/s2anet/blob/master/DOTA_devkit/polyiou/polyiou.py)，同样需要先将poly转成rbox， 才能使用。想问下，以上叙述是否正确，以及你是否研究过直接在poly(x1,y1,x2,y2,x3,y3,x4,y4) 的形式下，求overlaps的cuda代码，能否给些指导和分享？ 感谢！

**Comment by csuhan** [comment]
建议修改相关代码
https://github.com/csuhan/s2anet/blob/114fafadcb1fdc410893b42aa6db4f4f0d8c7dad/mmdet/ops/box_iou_rotated/src/box_iou_rotated_utils.h#L56-L75

**Comment by LiWentomng** [comment]
谢谢！ 经过修改调试后，目前得到了正常的结果！
