### ISSUE TITLE
Are there any differences between DOTA_devkit evaluation and coco 's segmentation evaluation api?

### ISSUE THREAD

**Issue by vpeopleonatank** [csuhan/s2anet#86]
I 'm trying to use coco 's segmentation evaluation api for DOTA competition 's task 1. Are there any differences between DOTA_devkit 's IOU calculation (in `voc_eval` function) and coco 's IOU calculation on segmentation metric?

**Comment by csuhan** [comment]
* DOTA uses VOC07 metrics, while COCO uses VOC12 metrics.
* DOTA task1 calculates IoU between polygons rather than rectangles.

**Comment by vpeopleonatank** [comment]
Thanks for clarification.
