### ISSUE TITLE
关于如何使用Albu数据增强

### ISSUE THREAD

**Issue by galaxyGGG** [csuhan/s2anet#89]
求问可以在config文件中的train_pipelines里设置albumentations的数据增强吗？例如：
```
albu_train_transforms = [
    dict(type='RandomBrightnessContrast'),
    dict(type="ShiftScaleRotate"),
    dict(type='RGBShift'),
    dict(type='Blur'), # 模糊
    dict(type='GaussNoise'), # 高斯噪声
    dict(type='Cutout')
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Albu', transforms=albu_train_transforms),
    dict(type='RandomRotate'),
    dict(type='RotatedResize', img_scale=(1024, 1024), keep_ratio=True),
    dict(type='RotatedRandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```

s2anet适用于哪些数据增强方法呢？谢谢！

**Comment by csuhan** [comment]
可直接适用：仅对图像增强，不对bbox变换的
对于需要同时修改bbox的，如resize，则需要修改对应的bbox处理函数。

**Comment by Lg955** [comment]
我想使用**没有数据旋转增强**的config文件来训练，我找到一个配置文件为`s2anet_r50_fpn_1x.py`，还有一个是`s2anet_r50_fpn_1x_ms_rotate.py`，我发现两个文件的区别在于：在`s2anet_r50_fpn_1x.py`里，rbox_head{……}设置了`with_orconv=True`，并且train_pipeline=[……]中取消了`dict(type='RandomRotate', rate=0.5, angles=[30, 60, 90, 120, 150], auto_bound=False),`；但是在`mmdet/models/anchor_heads/s2anet_head.py`中`self.with_orconv `缺省值为`True`，

    s2anet_r50_fpn_1x.py:

     rbox_head=dict(
        type='S2ANetHead',
        num_classes=16,
        in_channels=256,
        feat_channels=256,
        stacked_convs=2,
        align_conv_type='AlignConv',#[AlignConv,DCN,GA_DCN]
        align_conv_size=3,
        with_orconv=True,                       # s2anet_r50_fpn_1x_ms_rotate.py中没有这一句话
        anchor_ratios=[1.0],
        anchor_strides=[8, 16, 32, 64, 128],
        anchor_scales=[4],
        target_means=[.0, .0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0, 1.0],
        loss_fam_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_fam_bbox=dict(
            type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0),
        loss_odm_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_odm_bbox=dict(
            type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)))


    s2anet_r50_fpn_1x_ms_rotate.py

    train_pipeline = [
     dict(type='LoadImageFromFile'),
     dict(type='LoadAnnotations', with_bbox=True),
     dict(type='RotatedResize', img_scale=(1024, 1024), keep_ratio=True),
     dict(type='RotatedRandomFlip', flip_ratio=0.5),
     dict(type='RandomRotate', rate=0.5, angles=[30, 60, 90, 120, 150], auto_bound=False),  # s2anet_r50_fpn_1x_ms_rotate.py中没有这一句话
     dict(type='Normalize', **img_norm_cfg),
     dict(type='Pad', size_divisor=32),
     dict(type='DefaultFormatBundle'),
     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
  ]
 所以我的疑问是：只要注释掉`dict(type='RandomRotate', rate=0.5, angles=[30, 60, 90, 120, 150], auto_bound=False)`就可以不使用旋转数据增强，与`with_orconv=True`注不注释没有关系?(因为无论有没有 `with_orconv=True`，`self.with_orconv`均为True)

**Comment by csuhan** [comment]
> 只要注释掉dict(type='RandomRotate', rate=0.5, angles=[30, 60, 90, 120, 150], auto_bound=False)就可以不使用旋转数据增强，与with_orconv=True注不注释没有关系?

是的。with_orconv指的是：是否使用oriented response convolution

> DOTA-V1.0的label有两个，一个是labelTxt-v1.0, 还有一个是labelTxt-v1.5，这篇文章用的是labelTxt-v1.5吗？

v1.0. v1.5指的是DOTA-v1.5
