### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by PressEtoRace** [csuhan/s2anet#9]
Hi, During training ,when i set the "imgs_per_gpu=2, workers_per_gpu=2" in s2anet's config file, the error occurred. But when i change the two parameters to  "imgs_per_gpu=1, workers_per_gpu=1", it works. How can i solve the problem?

**Comment by csuhan** [comment]
Please post the full error log.

**Comment by PressEtoRace** [comment]
Hi, this is the full error log.

2020-10-03 05:27:08,056 - INFO - Distributed training: False
2020-10-03 05:27:08,450 - INFO - load model from: torchvision://resnet50
2020-10-03 05:27:08,638 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2020-10-03 05:27:12,476 - INFO - Start running, host: root@34b89899a490, work_dir: /user/lsc/workspace/s2anet/work_dirs/test
2020-10-03 05:27:12,476 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/user/lsc/workspace/s2anet/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/user/lsc/workspace/s2anet/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 17, in after_train_iter
    runner.outputs['loss'].backward()
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by csuhan** [comment]
Hi, @PressEtoRace , I guess some variables in AlignConv is not contiguous, but I have never encountered this problem in my experiments.
To fix it, you may need to:
1. check your dataset. If you are using DOTA or HRSC2016, please follow the installing guide.
2. add breakpoints in  ```mmdet.anchor_head.s2anet_head.S2ANetHead::forward``` to check whether the tensors are contiguous. (The errror log lacks of useful infomation.)

Looking forward to your reply.

**Comment by PressEtoRace** [comment]
Hi, Thanks for your reply!
1. Actually, I use my own dataset, it's labels are the same as the label in "./s2net/DOTA_devkit/example/labelTxt/". I follow the installing guide and use "DOTA_devkit/prepare_dota1_ms.py" to prepare my dataset, and i get the training set as:
![图片](https://user-images.githubusercontent.com/50652328/95006230-b1717180-0634-11eb-8293-d9c6f029436b.png)
When i set the "imgs_per_gpu=2, workers_per_gpu=2" in s2anet's config file, the config occurred. So how can i check my dataset?

2. I add "print(x.is_contiguous())" in forward(figure 1), and i get the result(figure 2). It means the variables is contiguous?
![图片](https://user-images.githubusercontent.com/50652328/95006373-8425c300-0636-11eb-864d-2fe8207c9e2b.png)
![图片](https://user-images.githubusercontent.com/50652328/95006382-9ef83780-0636-11eb-9c09-d55ab168e2ae.png)

**Comment by csuhan** [comment]
1. Check the image size. Change the image size to 1024*1024 to see if it will occur again.
2. You may need to add breakpoints in ```anchor2offset``` and after it. The inner variables may not be contiguous, even I have been very careful to avoid this problem.

**Comment by PressEtoRace** [comment]
Hi, @csuhan , I solved this problem by adding the code of "gradOutputBuffer = gradOutputBuffer.contiguous();" in line 431 of "./s2net/mmdet/ops/dcn/src/deform_conv_cuda.cpp", and I recompiled the s2net. Now, it works well, thanks for your help!

**Comment by csuhan** [comment]
I'm glad to hear that:grinning:

**Comment by Uncolor-Duck** [comment]
> Hi, @csuhan , I solved this problem by adding the code of "gradOutputBuffer = gradOutputBuffer.contiguous();" in line 431 of "./s2net/mmdet/ops/dcn/src/deform_conv_cuda.cpp", and I recompiled the s2net. Now, it works well, thanks for your help!

Thank you so much!!!

**Comment by shenhaibb** [comment]
> Hi, @csuhan , I solved this problem by adding the code of "gradOutputBuffer = gradOutputBuffer.contiguous();" in line 431 of "./s2net/mmdet/ops/dcn/src/deform_conv_cuda.cpp", and I recompiled the s2net. Now, it works well, thanks for your help!

Thank you very much for your suggestion
but I will not continue to run after adding it
Is it the wrong place I added？

![QQ20220727-203211@2x](https://user-images.githubusercontent.com/64736467/181247458-262f7775-21ec-4107-b32f-c3e758acc456.jpg)
