### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by dailonggang** [csuhan/s2anet#91]
为什么会出现KeyError: 'OHEMSampler is not in the bbox_sampler registry'，希望得到您的解答

**Comment by csuhan** [comment]
需要添加registry `@BBOX_SAMPLERS.register_module`
参考：
https://github.com/csuhan/s2anet/blob/114fafadcb1fdc410893b42aa6db4f4f0d8c7dad/mmdet/core/bbox/samplers/random_sampler.py#L7-L8

**Comment by dailonggang** [comment]
按照您所说的进行调整，代码已经顺利跑通，感谢您的帮助
