### ISSUE TITLE
感谢您的贡献，请问test.txt文件中存放的内容是什么呢？

### ISSUE THREAD

**Issue by qiujiayue** [csuhan/s2anet#94]
evaluation = dict(
    gt_dir='data/dota/test/labelTxt/',
    imagesetfile='data/dota/test/test.txt')

**Comment by csuhan** [comment]
Note train.txt and test.txt in HRSC2016 are .txt files recording image names without extension.

For example:

P00001
P00002
...

The same to DOTA.

**Comment by yzk-lab** [comment]
> Note train.txt and test.txt in HRSC2016 are .txt files recording image names without extension.
> 
> For example:
> 
> P00001 P00002 ...
> 
> The same to DOTA.

你好，测试集没有真实标签呢该怎么处理data/dota/test/labelTxt/呢？是在val集上这样设置吗？但是设置之后还是会弹出错误呢？error:P0003 我的val.txt已经改成了没有后缀的P0003 P0004...的格式了。麻烦告知 感谢。

**Comment by yzk-lab** [comment]
> Note train.txt and test.txt in HRSC2016 are .txt files recording image names without extension.
> 
> For example:
> 
> P00001 P00002 ...
> 
> The same to DOTA.

你好，测试集没有真实标签呢该怎么处理data/dota/test/labelTxt/呢？是在val集上这样设置吗？但是设置之后还是会弹出错误呢？error:P0003 我的val.txt已经改成了没有后缀的P0003 P0004...的格式了。麻烦告知 感谢。
