### ISSUE TITLE
关于mAP图像的绘制

### ISSUE THREAD

**Issue by Uncolor-Duck** [csuhan/s2anet#96]
我使用训练后模型的log文件与log.json文件，发现其中并没有AP与mAP的值，因此我在绘制曲线时无法使用--key mAP，我不知道这是由什么导致的。
如果是我忽视了中间步骤，请指教

**Comment by csuhan** [comment]
由于数据的原因，我们的代码目前没有实现online的测评，因此不包含AP和mAP。
