### ISSUE TITLE
Train with multiple GPUs

### ISSUE THREAD

**Issue by blank-97** [csuhan/s2anet#97]
使用单gpu训练时没有问题，但是使用多gpu训练时会卡在初始的位置，这是为什么呢？
<img width="1387" alt="截屏2021-08-03 下午3 49 32" src="https://user-images.githubusercontent.com/69951071/127978304-079bb10d-ad3b-40c8-910e-ef8f3b656d79.png">

**Comment by blank-97** [comment]
已解，目前成功实现了基于cuda11.1、pytorch1.8的s2anet，hrsc2016 map90.11。

**Comment by wangchengtza** [comment]
> 已解，目前成功实现了基于cuda11.1、pytorch1.8的s2anet，hrsc2016 map90.11。

您好 请问是怎么解决的，我单卡没问题，多卡就会卡住。

**Comment by blank-97** [comment]
> > 已解，目前成功实现了基于cuda11.1、pytorch1.8的s2anet，hrsc2016 map90.11。
> 
> 您好 请问是怎么解决的，我单卡没问题，多卡就会卡住。

建议看下log文件，确认一下是不是已经在训练了，因为会出现多卡训练时不打印log的情况。
